{% set name = "jupyterlab-stickyland" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_stickyland-{{ version }}.tar.gz
  sha256: a6f5a0cb65d3705b793e6c11b36c26e643208c2cbf6a68e325980b58661fa556

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - jupyterlab <=3.6.4
    - jupyter-packaging ~=0.10,<2
    - pip
    - python >=3.6
  run:
    - jupyterlab <=3.6.4
    - python >=3.6

test:
  imports:
    - jupyterlab_stickyland
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xiaohk/stickyland
  summary: Break free from the linear presentation of Jupyter Notebooks with sticky cells!
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
